[package]
name = "rust_struct"
version = "0.1.0"
edition = "2024"

[dependencies]
rust_ib2c_shared_data = { path = "../rust_ib2c_shared_data" }
serde = { version = "1.0.220", features = ["derive"] }
serde_json = "1.0.143"